apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wqb29w8x8-go 
  janus-idp.io/tekton: wqb29w8x8-go
  backstage.io/kubernetes-id: wqb29w8x8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wqb29w8x8-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml