apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wqb29w8x8-go
  janus-idp.io/tekton: wqb29w8x8-go
  backstage.io/kubernetes-id: wqb29w8x8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wqb29w8x8-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
