apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wqb29w8x8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wqb29w8x8-go 
  name: wqb29w8x8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wqb29w8x8-go 
